version: '3.8'

services:
  discord-bot:
    build: .
    container_name: kotlin-discord-bot
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"